// Mocks generated by Mockito 5.0.16 from annotations
// in mobile_buyer_flutter/test/phone_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mobile_buyer_flutter/data_layer/api_services.dart' as _i3;
import 'package:mobile_buyer_flutter/data_layer/phone.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeClient_0 extends _i1.Fake implements _i2.Client {}

/// A class which mocks [ApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServices extends _i1.Mock implements _i3.ApiServices {
  MockApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient_0()) as _i2.Client);
  @override
  _i4.Future<List<_i5.Phone>> fetchPhoneList() =>
      (super.noSuchMethod(Invocation.method(#fetchPhoneList, []),
              returnValue: Future<List<_i5.Phone>>.value(<_i5.Phone>[]))
          as _i4.Future<List<_i5.Phone>>);
  @override
  String toString() => super.toString();
}
